# Generated by Django 6.0.4 on 2026-04-24 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('input_query', models.TextField()),
                ('expected_answer', models.TextField(blank=True)),
                ('expected_schema', models.JSONField(null=True)),
                ('rubric', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template_name', models.CharField(max_length=100)),
                ('prompt_version_number', models.PositiveIntegerField()),
                ('total_cases', models.PositiveIntegerField()),
                ('passed_cases', models.PositiveIntegerField()),
                ('pass_rate', models.FloatField()),
                ('avg_latency_ms', models.FloatField()),
                ('total_cost_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_FLIGHT', 'In Flight'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by Guardrail')], db_index=True, default='PENDING', max_length=20)),
                ('prompt_template_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version_number', models.PositiveIntegerField(null=True)),
                ('raw_query', models.TextField()),
                ('rendered_prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('fallback_used', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('input_blocked', models.BooleanField(default=False)),
                ('input_block_reason', models.CharField(blank=True, max_length=200)),
                ('output_blocked', models.BooleanField(default=False)),
                ('truncation_applied', models.BooleanField(default=False)),
                ('turns_removed', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_class', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Request Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField()),
                ('result', models.JSONField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('iteration', models.PositiveSmallIntegerField(default=1)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='instrumentation.llmrequestlog')),
            ],
        ),
    ]
